# Generated by Django 6.0.3 on 2026-04-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EduTest', max_length=100)),
                ('header_phone', models.CharField(default='+998 71 000 00 00', max_length=30)),
                ('ticker_text', models.TextField(default='Ushbu platforma yordamida o‘z bilimingizni sinab ko‘rishingiz mumkin va o‘z reyting natijalaringiz bilan tanishib olasiz')),
                ('ticker_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Platforma sozlamasi',
                'verbose_name_plural': 'Platforma sozlamalari',
            },
        ),
    ]
