# Generated by Django 6.0.3 on 2026-04-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='required_subject_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
