# Generated by Django 6.0.3 on 2026-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings_required_subject_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='minutes_per_subject',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
