# Generated by Django 6.0.3 on 2026-03-28 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
