# Generated by Django 6.0.3 on 2026-04-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attempts', '0002_testsession_testsessionanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='total_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
